---
title: "Final Project"
author: "Raghed Al Farawati"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TITLE
### Raghed Al Farawati
### `r format(Sys.Date(), '%B %d, %Y')`


# Introduction
In .docx


# Packages Required
In .docx

```{r libraries}
suppressWarnings({ # warnings suppression is due to the assignment requirements 
  library(rmarkdown) # this package is for dynamic markdown (.rmd) file
  library(tidyverse) # this package is main package for data manipulation and                           tidying 
  library(tidyr) # this package is for tidying the data
  library(tibble) # this package is for creating tibbles and re-imaging the data                     frame
  library(dplyr) # this package is for data manipulation  
  library(ggplot2) # this package is for data visualization 
  library(shiny)
})

```


# Data Preparation 
In .docx

**Source:** Data Axle & Kinder Institute For Urban Research-Urban Data Platform Team. (2021). Counts of Manufacturing Businesses - Houston MSA - 2018-2021 (Version 1) [dataset]. Rice University. <https://doi.org/10.25612/837.RDB506Y63571>.

*Hold Shift key on keyboard for clicking the link*





```{r locate}
# Locate files in the directory.
getwd()
```

```{r load data}
# Load the data set for project. 
file_path1 <- "C:\\Users\\raghe\\OneDrive - University of Houston Downtown\\Documents\\Classes\\2023 - 2024\\Spring 2024\\DATA 2401-01 CRN #20969\\Course Work\\Final Project\\Final Project\\manuf2018plus.csv"
manuf2018plus <- read_csv(file_path1)

file_path2 <- "C:\\Users\\raghe\\OneDrive - University of Houston Downtown\\Documents\\Classes\\2023 - 2024\\Spring 2024\\DATA 2401-01 CRN #20969\\Course Work\\Final Project\\Final Project\\manuf2018plus_code.csv"
manuf2018plus_code <- read_csv(file_path2)

file_path3 <- "C:\\Users\\raghe\\OneDrive - University of Houston Downtown\\Documents\\Classes\\2023 - 2024\\Spring 2024\\DATA 2401-01 CRN #20969\\Course Work\\Final Project\\Final Project\\vi_manuf2018plus.csv"
vi_manuf2018plus <- read_csv(file_path3)
```
```{r view data}
glimpse(manuf2018plus)
glimpse(manuf2018plus_code)
glimpse(vi_manuf2018plus)
```

```{r}

```

